### ISSUE TITLE
Album page markup of issues.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#20]
I made a markup of some of the items I believe to be issues.  Have a look and see what you think.
[](url)http://i725.photobucket.com/albums/ww260/killhellokitty1/Screenshot%20from%202016-07-23%2014-38-35_zpsflyykzxo.png

**Comment by othmar52** [comment]
thanks a lot for all your feedback! its really helpful

those issues you mentioned:

**A) weightening of images based on filenames**
this is not implemented yet. Currently the weigtening is done by filesize to avoid tiny thumbnails beeing choosed as primary image. Feel free to open a separate issue for that.

**B) broken layout of album meta infos**
this did not appear in german version so i missed that. pull the [latest commits](https://github.com/othmar52/slimpd/commit/ad59eb19a78d4803276b44d22ac6eb8759e234ca) to have it fixed.

**C) invalid sorting of tracks**
valid point! due to an unfinished issue within extracting/guessing those tracknumbers it was not that important for me. anyway - it should be fixed in the [latest commits](https://github.com/othmar52/slimpd/commit/5db29b1c490ab72e4616a4f62064bef2a4a701a6) but i am pretty sure that you see invalid tracknumbers from time to time which will cause an invalid sorting as well.


**D) editing of tracks/albums does not work**
This is not implemented yet. As this is an enourmous task (bigger than sliMpd project itself) don't expect to have this working & stable in near future.

**Comment by killhellokitty** [comment]
Thanks for getting back to me so soon.  I will open an issue for the
weighted images.  The file-size of the initial image can be forced with
imagemagik.
I'll check out the latest commits for b and c.  And I had a feeling D was
going to be unimplemented and difficult to achieve.

Its coming along very nicely.  I want to try out the xwax I was a DJ in Las
Vegas some years back and still have my vinyl and CD turntables, my current
living situation makes it difficult to try them out, but I will see what I
can do.

**Comment by killhellokitty** [comment]
The page looks much better the album/track info makes sense and is well placed.  And the tracks are listed by number 1,2,3,4...
