### ISSUE TITLE
filetype quicktime - Losless compression, wrong name

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#25]
Under file type it should list this as M4A or m4a, it is actually MPEG-4 Audio.
It is: advanced audio coding (AAC) losless format.  Quicktime is an incorrect description of the codec.

**Comment by othmar52** [comment]
scanning metadata of music files is down by an external library ([JamesHeinrich/getID3](https://github.com/JamesHeinrich/getID3))

i have [added](https://github.com/othmar52/slimpd/commit/5cbca436e3379f090adb0af50689d2d9aed9b4c5) another debug possibility `trackwidget -> edit -> dump metadata`
[![new link for dumping metadata](http://gas-werk.org/slimpd/2016-07/dump-meta-link.png)](http://gas-werk.org/slimpd/2016-07/dump-meta-link.png)

I think the issue should be reported to the getId3 repo!? maybe the problem is related to [this issue](https://github.com/JamesHeinrich/getID3/issues/48).

**Comment by killhellokitty** [comment]
For the time being I would do something like was suggested:

Meanwhile you can do something like
$info['mime_type'] = ((($info['mime_type'] == 'audio/quicktime') &&
preg_match('#\\.(m4a)$#i', $info['filename']) ? 'audio/m4a' :
$info['mime_type']);
where $info is the array returned from getid3->analyze and that should
modify the MIME type based on filename.

As it doesn't appear as though the author has any intention of making any
changes to what is seen as a Quicktime mime type.  I suggest you attempt to
add the suggested workaround.  Because Quicktime-codec and M4A are not the
same thing.  Anyone who has ever owned a Mac and worked with audio knows
the difference.

Regards
Josh

**Comment by killhellokitty** [comment]
Fixed
