### ISSUE TITLE
Now Playing page error/issues.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#26]
The Now Playing Track page has some issues that you should take a look at.  [](url)<a href="http://s725.photobucket.com/user/killhellokitty1/media/Screenshot%20from%202016-07-27%2014-22-18_zpserm1ixuy.png.html" target="_blank"><img src="http://i725.photobucket.com/albums/ww260/killhellokitty1/Screenshot%20from%202016-07-27%2014-22-18_zpserm1ixuy.png" border="0" alt="Track Playing sliMpd photo Screenshot from 2016-07-27 14-22-18_zpserm1ixuy.png"/></a>

**Comment by othmar52** [comment]
> Embedded cover image that was not imported

This should be fixed since [deactivating a size check](https://github.com/othmar52/slimpd/issues/11#issuecomment-235815237)

> When button is pressed, visually nothing happens

This should be fixed (autorefresh when playlist changes and/or when currently played track changes)

> ...#CAT ... TODO:STYLE ...

I added those labels a long time ago after a mate of me created a raw scribble of sliMpd's possible layout.
[![sliMpd scribble November 2015][2]][1]
  [1]: http://gas-werk.org/slimpd/scribbles/ixwax_Now_Playing_2015-11-07.jpg
  [2]: http://gas-werk.org/slimpd/scribbles/ixwax_Now_Playing_2015-11-07-thumb.jpg

Anyway - i have improved the layout. Please pull the latest commits and give it a try

**Comment by killhellokitty** [comment]
The embedded cover image import works like a charm.

The 'Clear Playlist" button works! and it keeps accurate count of the
playlist tracks before and after being pressed.

The layout looks much better.  Cleaner.

Nice Job!
