### ISSUE TITLE
Support for HTTP Stream

### ISSUE THREAD

**Issue by wengxt** [othmar52/slimpd#54]
Personally I use mpd and its http stream feature. I would like to see if slimpd can support directly play the mpd stream from browser. (I'm aware that slimpd can play files directly, but still..)

**Comment by othmar52** [comment]
@wengxt 
Within a quick hack i tried to open `http://my-mpd-ip:1234` with the javascript-player and it worked without any problems.

the problem is: this javascript player is currently only available in "local player mode". switching to "mpd player mode" stops the local player. se we have to work out a concept that does make sense.

In my opinion this "stream"-link should only be available in "mpd mode". do you have any ideas how to implement this in the GUI?

what happens on toggling to "local mode" with an active mpd stream inside the "mpd mode"?
should this stop the mpd http stream? or should the mpd http stream be loaded in the local player as well?

would be great if you come up with a concept. it would be fun for me to implement this feature.

**Comment by wengxt** [comment]
I guess the reason I want to use mpd's own stream is its player state is stored on the server, and I can restore that state from anywhere.

Other than the web client, I use canata on desktop and mpdroid on android. The cantata's configuration looks like this, so basically it's an additional field sits along with the mpd's host and port.

![image](https://cloud.githubusercontent.com/assets/259684/24595044/9c0336ce-17e7-11e7-8069-6e45b8e6b440.png)

Right now if local is playing and mpd mode is clicked, the local player will pause, I think it is totally fine to keep this behavior.

So what I'd expect to see is:
- when entering mpd mode, if there's a stream url configured, and mpd state is "play", play the stream. otherwise stop it
- When leaving mpd mode, stop the stream.

**Comment by othmar52** [comment]
@wengxt 
I dont like the idea of playing audio in the browser directly after switching to mpd-mode.
so i have added a button in the mpd-player for starting the stream manually

please pull the latest commit and add something like this to your `core/config/config_local.ini`
```ini
[mpd]
http_stream_url = "http://192.168.1.20:1234"
```
due to some caching issues remove the cached config manually
```
rm localdata/cache/conf*
```

and give it a try

**Comment by othmar52** [comment]
@wengxt 
does it work for you?

**Comment by wengxt** [comment]
Sorry I didn't have time to check it before. I just updated to git master and it works great! Thank you!

There seems to be a small display problem though. When I click play a song, the mpd-stream button will become grey while it is still playing.

**Comment by othmar52** [comment]
@wengxt Thank you for your feedback. In case you find more bugs, don't hesitate to create new issues.
